### ISSUE TITLE
Off topic question about BorgBackup

### ISSUE THREAD

**Issue by morlandi** [christianwgd/django_restic_gui#15]
@christianwgd may I ask whether you had the chance to compare Restic vs BorgBackup ?

I'm still evaluating a solution to work with, and so far I'm really happy with Restic, although would probably feel more confortable with a solution based on Python instead of Go

**Comment by christianwgd** [comment]
Of cause, you may ask ;-) but no, i didn’t evaluate BorgBackup.

**Comment by morlandi** [comment]
thank you, there are plenty of articles on this issue, but in case a real personal opinion from you would have been interesting to hear.
Never mind, let's close this issue ;)
